### ISSUE TITLE
Exception when loading a repo

### ISSUE THREAD

**Issue by Vadiml1024** [Shubhamsaboo/awesome-llm-apps#12]
I get following stacktrace:
`Traceback (most recent call last):
  File "/Users/vadim/work/awesome-llm-apps/chat_with_github/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/Users/vadim/work/awesome-llm-apps/chat_with_github/chat_github_llama3.py", line 29, in <module>
    app = embedchain_bot(db_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/work/awesome-llm-apps/chat_with_github/chat_github_llama3.py", line 15, in embedchain_bot
    return App.from_config(
           ^^^^^^^^^^^^^^^^
  File "/Users/vadim/work/awesome-llm-apps/chat_with_github/.venv/lib/python3.12/site-packages/embedchain/app.py", line 381, in from_config
    init_db()
  File "/Users/vadim/work/awesome-llm-apps/chat_with_github/.venv/lib/python3.12/site-packages/embedchain/core/db/database.py", line 80, in init_db
    alembic_upgrade()
  File "/Users/vadim/work/awesome-llm-apps/chat_with_github/.venv/lib/python3.12/site-packages/embedchain/core/db/database.py", line 76, in alembic_upgrade
    command.upgrade(alembic_cfg, "head")
  File "/Users/vadim/work/awesome-llm-apps/chat_with_github/.venv/lib/python3.12/site-packages/alembic/command.py", line 394, in upgrade
    with EnvironmentContext(
  File "/Users/vadim/work/awesome-llm-apps/chat_with_github/.venv/lib/python3.12/site-packages/alembic/runtime/environment.py", line 218, in __exit__
    self._remove_proxy()
  File "/Users/vadim/work/awesome-llm-apps/chat_with_github/.venv/lib/python3.12/site-packages/alembic/util/langhelpers.py", line 87, in _remove_proxy
    del globals_[attr_name]
        ~~~~~~~~^^^^^^^^^^^
KeyError: 'config'
2024-05-21 06:40:01.049 Uncaught app exception
`
I' ve edited the offending line to be:
```
  if attr_name in globals_: 
     del globals_[attr_name]

```

This allowed me to proceed

**Comment by Shubhamsaboo** [comment]
Thanks for sharing!
