### ISSUE TITLE
httpcore.ConnectError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by dep** [Shubhamsaboo/awesome-llm-apps#22]
After running through the instructions [here](https://x.com/saboo_shubham_/status/1819922958502215755) I receive the following error while querying via the UI:

```
2024-08-05 09:51:11.750 Uncaught app exception
Traceback (most recent call last):
  File "/Users/dpeck/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/dpeck/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/Users/dpeck/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/Users/dpeck/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/Users/dpeck/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/dpeck/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/Users/dpeck/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/Users/dpeck/Library/Python/3.9/lib/python/site-packages/httpcore/_backends/sync.py", line 213, in connect_tcp
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/dpeck/Library/Python/3.9/lib/python/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 61] Connection refused
```

**Comment by Shubhamsaboo** [comment]
Did you do? 

`ollama run llama3.1`

It makes sure that the model is running on your local machine.
