### ISSUE TITLE
Problem running chat with pdf

### ISSUE THREAD

**Issue by Vadiml1024** [Shubhamsaboo/awesome-llm-apps#3]
I'm getting following:
  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.9:8501

2024-05-02 19:07:35.047 Uncaught app exception
Traceback (most recent call last):
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table ec_chat_history already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/home/vadim/Work/awesome-llm-apps/chat_with_pdf/chat_pdf.py", line 29, in <module>
    app = embedchain_bot(db_path, access_token)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vadim/Work/awesome-llm-apps/chat_with_pdf/chat_pdf.py", line 10, in embedchain_bot
    return App.from_config(
           ^^^^^^^^^^^^^^^^
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/embedchain/app.py", line 381, in from_config
    init_db()
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/embedchain/core/db/database.py", line 80, in init_db
    alembic_upgrade()
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/embedchain/core/db/database.py", line 76, in alembic_upgrade
    command.upgrade(alembic_cfg, "head")
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/embedchain/migrations/env.py", line 68, in <module>
    run_migrations_online()
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/embedchain/migrations/env.py", line 62, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/embedchain/migrations/versions/40a327b3debd_create_initial_migrations.py", line 23, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/alembic/operations/ops.py", line 1311, in create_table
    return operations.invoke(op)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/alembic/operations/base.py", line 445, in invoke
    return fn(self, operation)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/alembic/operations/toimpl.py", line 131, in create_table
    operations.impl.create_table(table)
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/alembic/ddl/impl.py", line 366, in create_table
    self._exec(schema.CreateTable(table))
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/alembic/ddl/impl.py", line 207, in _exec
    return conn.execute(construct, multiparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
           ^^^^^
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1533, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/vadim/Work/awesome-llm-apps/.env/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table ec_chat_history already exists
[SQL: 
CREATE TABLE ec_chat_history (
	app_id VARCHAR NOT NULL, 
	id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	question TEXT, 
	answer TEXT, 
	metadata TEXT, 
	created_at TIMESTAMP, 
	PRIMARY KEY (app_id, id, session_id)
)

]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by Shubhamsaboo** [comment]
I tried this on my end but not able to replicate the error.

**Comment by Shubhamsaboo** [comment]
Closing this as there was no response for a while.
